import {Component} from '@angular/core';
import { Employee } from './model/Employee';
import {HttpClient, HttpHeaders} from "@angular/common/http";
import {Observable, of} from "rxjs";
import { BearerTokenHolderService } from './service/bearer-token-holder.service';
import { EmployeeService } from './service/employee.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  bearer = 'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIzUFQ0dldiNno5MnlQWk1EWnBqT1U0RjFVN0lwNi1ELUlqQWVGczJPbGU0In0.eyJleHAiOjE2NDMyMDg1NDAsImlhdCI6MTY0MzE5NDE0MCwianRpIjoiZDVkN2YwODAtNGUwMi00YmYwLWEwZDctMGFiZmRkNTcwMTQ5IiwiaXNzIjoiaHR0cHM6Ly9rZXljbG9hay5zenV0LmRldi9hdXRoL3JlYWxtcy9zenV0IiwiYXVkIjoiYWNjb3VudCIsInN1YiI6IjU1NDZjZDIxLTk4NTQtNDMyZi1hNDY3LTRkZTNlZWRmNTg4OSIsInR5cCI6IkJlYXJlciIsImF6cCI6ImVtcGxveWVlLW1hbmFnZW1lbnQtc2VydmljZSIsInNlc3Npb25fc3RhdGUiOiIwNmU5Yzk1Yi1mMzJmLTRmNTUtYTMyNC1iMDI0YzM4NzYwNDAiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwiZGVmYXVsdC1yb2xlcy1zenV0IiwidW1hX2F1dGhvcml6YXRpb24iLCJ1c2VyIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.PJhdBAzJf4Jsk1TRJhu1HiFBg75zfiekt55CNVhPX4bCKxEdb0Rb2pVSJ1d9KGghWXIU3iuQDDtIYPRVFABzpnFZRi0IhS-j9C34WwQF9roKJnMEmMoGBWjc-2QDKMRkGyAPpBge-2VL_T66hLqiIy-bRsSBfmQbfQPxjxY3X6v9yiv-fqjcR9h4dNc2PUNpryn5yq8TLDq41dJ94Ybl1JO7nAqWvUoXoi2gc3Se8IWY890nExd8oeUWyp_zoom5Fq9LOVAeIZzbqZ8xHcOuWxwidzRBJZBlDYK2lMNX5l2ttp-amVna7LiPq2ILniQuvSvQMpFE2VOBqzzbb1uMfg';

  constructor() {

  }
}
